### ISSUE TITLE
Add Support for New Gophercloud Services

### ISSUE THREAD

**Issue by jtopjian** [theopenlab/openlab-zuul-jobs#143]
Gophercloud has recently added support for:

* Zaqar / Messaging
* Senlin / Clustering
* Octavia / LBaaS

We'd like to have OpenLab be able to run the acceptance tests for these services.

**Comment by mrhillsman** [comment]
@kiwik @animationzl @liu-sheng

**Comment by mrhillsman** [comment]
related theopenlab/openlab/issues/17

If gophercloud does not require any secrets we need to move to gophercloud repo to empower gophercloud community to manage their jobs

**Comment by jtopjian** [comment]
That would be cool :)

I've been working on cleaning up the Gophercloud acceptance tests in order to enable more tests to run: https://github.com/gophercloud/gophercloud/issues/818

Enabling/disabling tests ourselves would certainly help us as well as relieve some responsibility on your end :)

**Comment by mrhillsman** [comment]
@jtopjian will work to ensure this happens sooner than later ;)

**Comment by mrhillsman** [comment]
@yihleong can we get someone looking into assisting here

**Comment by hongbin** [comment]
I take the Octavia part. @tengqm anyone from your team volunteers for the Senlin part. @openstacker anyone from your team volunteers for the Zaqar part?

**Comment by hongbin** [comment]
@tengqm the original request is from gophercloud maintainers who wanted to run acceptance tests in their CI against Senlin devstack deployment. This repo contains the configuration of gophercloud jobs. The requirement is to enable Senlin in gophercloud jobs. See here as an example: https://github.com/theopenlab/openlab-zuul-jobs/pull/147

**Comment by tengqm** [comment]
@hongbin Thanks for the hints. I'm still confused by the work items. Refer to this one: https://github.com/gophercloud/gophercloud/issues/823 There are not enough concepts merged to do any useful functional/integration tests for Senlin. 

Do you (or others) mean that we can enable Senlin on TheOpenLib in a separate thread? I'm more than happy to see this happen. However, I do not want to introduce changes that may break the existing test jobs.

**Comment by hongbin** [comment]
@tengqm my understanding is:

* This repo contains the configuration of the gophercloud that basically stand up an openstack deployment using devstack
* The actual test cases are living at somewhere else (possibly in gophercloud repo).

If you or someone else wants to enable Senlin in the CI, the first step is to submit a PR to this repo to configure devstack to install Senlin. Then, you are ready to write test cases for Senlin.

**Comment by jtopjian** [comment]
I'm going to go ahead and close this since Gophercloud now has the ability to do this.

Thank you to everyone who helped with this 😄

**Comment by mrhillsman** [comment]
@jtopjian thx
