### ISSUE TITLE
Integrate with k8s

### ISSUE THREAD

**Issue by animationzl** [theopenlab/openlab-zuul-jobs#27]
Integrate the k8s with OpenLab system

**Comment by yongfengdu** [comment]
I'll be investigating on bring up the k8s deployment first based on dims' work https://github.com/dims/openstack-cloud-controller-manager.

**Comment by kiwik** [comment]
Let us enumerate all scenarios of kubernetes and OpenStack integration at first, then implement each one in separate ansible jobs.

**Comment by kiwik** [comment]
1. UT: dims/openstack-cloud-controller-manager + devstack **[in vm]**
2. UT: kubernetes/kubernetes/pkg/cloudprovider/providers/openstack + devstack **[in vm]**
3. Functionality: dims/openstack-cloud-controller-manager + devstack with LB and Octavia **[out of vm]**
4. Functionality: dims/openstack-cloud-controller-manager + kubernetes.io/cinder provisioner + devstack **[in vm]**
5. Functionality: dims/openstack-cloud-controller-manager + openstack.org/standalone-cinder provisioner + devstack **[out of vm]**
6. Functionality: dims/openstack-cloud-controller-manager + flexvolume cinder driver + devstack **[out of vm]**
7. Functionality: dims/openstack-cloud-controller-manager + CSI cinder plugin + devstack **[in vm]**
8. Functionality: dims/openstack-cloud-controller-manager + Keystone auth + devstack **[out of vm]**
9. _Add new scenario_

All of these test run against OpenStack and Kubernetes master, we will try to test specific version in next step.

**Comment by kiwik** [comment]
This issue to list all of the scenarios, and each scenario should be implemented in separate issue and PR.

**Comment by kiwik** [comment]
All of the scenarios should be run in a vm that boot from OpenStack.

**Comment by kiwik** [comment]
All of work items are finished, close the issue.
