### ISSUE TITLE
Guide for job logs

### ISSUE THREAD

**Issue by liu-sheng** [theopenlab/openlab-zuul-jobs#29]
Sometimes, job may run failed because building failure,  that may lead the testing results cannot be correctly formatted and the "test_results.html" maybe empty.  Developers can find the root cause in "job-output.txt.gz", it is better to add a guide about how to read the logs. like web page[1].

[1] http://logs.openstack.org/53/539953/1/check/legacy-tempest-dsvm-py35/6f7497e/

**Comment by kiwik** [comment]
Now we don't copy empty test_results.html to log server in https://github.com/theopenlab/openlab-zuul-jobs/pull/135/files#diff-f9ad47868c7ce8bf9eea21543ef48379 , that reduce some confusion.
