### ISSUE TITLE
Terraform and Gophercloud: network "trunk" extension

### ISSUE THREAD

**Issue by jtopjian** [theopenlab/openlab-zuul-jobs#341]
Hello,

I wasn't sure where else to request this. Gophercloud recently added support for the networking "trunk" extension, but the PRs moved too fast to request this within one of them.

It doesn't look like the devstack configuration enables the "trunk" extension. Would it be possible to add this?

**Comment by mrhillsman** [comment]
hey @jtopjian just seeing this, apologies, we can definitely enable it or if you know the change(s) needed feel free to create the PR

**Comment by jtopjian** [comment]
@mrhillsman Thanks! Unfortunately I don't know what changes would be needed. But if someone links the patch to this Issue, it might give me a good idea of how to do it for future features :)

**Comment by kiwik** [comment]
theopenlab/openlab#92 have been addressed, close this issue.
