### ISSUE TITLE
Integrate with terraform-provider-flexibleengine

### ISSUE THREAD

**Issue by animationzl** [theopenlab/openlab-zuul-jobs#53]
Integrate terraform-provider-flexibleengine[1] with OpenLab CI to test against Orange Cloud[2].
For https://github.com/orgs/theopenlab/projects/1#card-7214218

[1] https://github.com/Karajan-project/terraform-provider-flexibleengine
[2] http://cloud.orange-business.com/en/

**Comment by kiwik** [comment]
https://github.com/theopenlab/openlab-zuul-jobs/pull/52 have been merged. all work items are finished?

**Comment by kiwik** [comment]
Finish all, closed
