### ISSUE TITLE
Add new node resources provided by Open Telekom Cloud to nodepool

### ISSUE THREAD

**Issue by animationzl** [theopenlab/openlab-zuul-jobs#65]
A group of new node resources under a specific Open Telekom Cloud account are supplemented to nodepool to provide large standard nodes for k8s integration purpose.

**Comment by kiwik** [comment]
If we have finished the configuration of nodepool, please close the issue.

**Comment by kiwik** [comment]
Currently we have **ubuntu-xenial-large** in OpenLab nodepool to support Kubernetes nested vm scenario.
